### ISSUE TITLE
点击获取二维码无反应

### ISSUE THREAD

**Issue by wssysh** [ultrazg/cloudmusic-uploder-front-end#1]
你好，我按照说明运行打开页面后无法获取二维码，edge与firedox都不行。以下是后台显示信息：

Compiled with warnings.

[eslint] 
src/layout/aboutModal/index.tsx
  Line 26:11:  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank

src/pages/index/index.tsx
  Line 128:15:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/layout/aboutModal/index.tsx
  Line 26:11:  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank

src/pages/index/index.tsx
  Line 128:15:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

webpack compiled with 1 warning
No issues found.

**Comment by ultrazg** [comment]
eslint 警告问题已修复。本项目的运行依赖 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)，请在 clone 并成功启动 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 后运行本项目

**Comment by zhijiwuyan** [comment]
扫码登录过程中 手机扫码成功 但是api返回的code一直却是801 目前没查出代码有啥逻辑错误

vuex：
 //显示二维码 
    ShowQRcode: async function(context, value) {
      let res = await getLoginerweima(value)
      // 生成的unikey 赋值
      context.state.loginUnikey= res.data.data.unikey
      let res02 = await getLoginerweima02(context.state.loginUnikey)
      context.state.loginQRcode=res02.data.data.qrimg
      console.log(context.state.loginUnikey)

    },
    QRlogin: async function (context, value) {
      console.log(context.state.loginUnikey)
      let res=await getLoginerweima03(context.state.loginUnikey)
      return res
    },

请求接口
// 登陆页面的登录接口 二维码登录
export function getLoginerweima(data) {
    return service({
        method:'get',
        url:`/login/qr/key?timestamp=${Date.now()}`,
    })
}
// 登陆页面的登录接口 二维码登录
export function getLoginerweima02(data) {
    return service({
        method:'get',
        url:`/login/qr/create?key=${data}&qrimg=true&timestamp=${Date.now()}`,
    })
}
// 二维码检测扫码状态接口 /login/qr/check?key=xxx
export function getLoginerweima03(data) {
    return service({
        method:'get',
        url:`/login/qr/check?key=${data}&timestamp=${Date.now()}`,
    })
}
  // 扫码登录
    async login02() {
      let res = await this.QRlogin();
      console.log(res.data.code);
     
    },

**Comment by zhijiwuyan** [comment]
> 扫码登录过程中 手机扫码成功 但是api返回的code一直却是801 目前没查出代码有啥逻辑错误
> 
> vuex： //显示二维码 ShowQRcode: async function(context, value) { let res = await getLoginerweima(value) // 生成的unikey 赋值 context.state.loginUnikey= res.data.data.unikey let res02 = await getLoginerweima02(context.state.loginUnikey) context.state.loginQRcode=res02.data.data.qrimg console.log(context.state.loginUnikey)
> 
> ```
> },
> QRlogin: async function (context, value) {
>   console.log(context.state.loginUnikey)
>   let res=await getLoginerweima03(context.state.loginUnikey)
>   return res
> },
> ```
> 
> 请求接口 // 登陆页面的登录接口 二维码登录 export function getLoginerweima(data) { return service({ method:'get', url:`/login/qr/key?timestamp=${Date.now()}`, }) } // 登陆页面的登录接口 二维码登录 export function getLoginerweima02(data) { return service({ method:'get', url:`/login/qr/create?key=${data}&qrimg=true&timestamp=${Date.now()}`, }) } // 二维码检测扫码状态接口 /login/qr/check?key=xxx export function getLoginerweima03(data) { return service({ method:'get', url:`/login/qr/check?key=${data}&timestamp=${Date.now()}`, }) }  
登录页面
// 扫码登录 async login02() { let res = await this.QRlogin(); console.log(res.data.code);
> 
> ```
> },
> ```

**Comment by zhijiwuyan** [comment]
登录页面内容
  // 扫码登录
    async login02() {
      let res = await this.QRlogin();
      console.log(res.data.code);
    },
api 
// 登陆页面的登录接口 二维码登录 
export function getLoginerweima(data) {
    return service({
        method:'get',
        url:`/login/qr/key?timestamp=${Date.now()}`,
    })
}
// 登陆页面的登录接口 二维码登录 
export function getLoginerweima02(data) {
    return service({
        method:'get',
        url:`/login/qr/create?key=${data}&qrimg=true&timestamp=${Date.now()}`,
    })
}
// 二维码检测扫码状态接口 /login/qr/check?key=xxx
export function getLoginerweima03(data) {
    return service({
        method:'get',
        url:`/login/qr/check?key=${data}&timestamp=${Date.now()}`,
    })
}

vuex：
 //显示二维码 
    ShowQRcode: async function(context, value) {
      let res = await getLoginerweima(value)
      // 生成的unikey 赋值
      context.state.loginUnikey= res.data.data.unikey
      let res02 = await getLoginerweima02(context.state.loginUnikey)
      context.state.loginQRcode=res02.data.data.qrimg
      console.log(context.state.loginUnikey)

    },
    QRlogin: async function (context, value) {
      let res=await getLoginerweima03(context.state.loginUnikey)
      return res
    },
在登陆页面扫码登陆时 手机端提示授权成功  pc返回的一直是code值为801  拿不到cookie
